# Generated by Django 6.1.1 on 2026-09-23 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('organizations', '0002_one_main_campus_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BellSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bell_schedules', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'timetable_bell_schedule',
                'ordering': ['campus', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False, help_text="Breaks can't have lessons.")),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetable.bellschedule')),
            ],
            options={
                'db_table': 'timetable_period',
                'ordering': ['schedule', 'start_time', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='timetable.period')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.room')),
                ('teaching_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.teachingassignment')),
                ('term', models.ForeignKey(blank=True, help_text='Empty: runs the whole academic year.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.term')),
            ],
            options={
                'verbose_name_plural': 'timetable entries',
                'db_table': 'timetable_entry',
                'ordering': ['day_of_week', 'period__start_time', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='bellschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('campus', 'name'), name='uniq_bell_schedule_name'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('schedule', 'name'), name='uniq_period_name'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='period_times_ordered'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['organization', 'day_of_week'], name='timetable_e_organiz_219bcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='timetable_entry_weekday'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('term__isnull', True)), fields=('teaching_assignment', 'day_of_week', 'period'), name='uniq_timetable_entry_all_year'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('term__isnull', False)), fields=('teaching_assignment', 'day_of_week', 'period', 'term'), name='uniq_timetable_entry_term'),
        ),
    ]
