# Generated by Django 6.1.1 on 2026-09-23 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_teachingassignment_periods_per_week_studentelective'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='combined_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='Entries with the same value are one combined class of several sections.', null=True),
        ),
        migrations.CreateModel(
            name='LessonChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='timetable.timetableentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('room', models.ForeignKey(blank=True, help_text='Where the lesson moves to that day.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_changes', to='academics.room')),
                ('substitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='staff.staffmember')),
            ],
            options={
                'db_table': 'timetable_lesson_change',
                'ordering': ['date', 'entry__period__start_time', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('entry', 'date'), name='uniq_lesson_change'), models.CheckConstraint(condition=models.Q(models.Q(('is_cancelled', True), ('room__isnull', True), ('substitute_teacher__isnull', True)), models.Q(('is_cancelled', False), models.Q(('substitute_teacher__isnull', False), ('room__isnull', False), _connector='OR')), _connector='OR'), name='lesson_change_is_meaningful')],
            },
        ),
    ]
