# Generated by Django 6.1.1 on 2026-09-23 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_dated_electives_assignment_roles'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('timetable', '0002_timetableentry_combined_group_lessonchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='period',
            name='uniq_period_name',
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='uniq_timetable_entry_all_year',
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='uniq_timetable_entry_term',
        ),
        migrations.AddField(
            model_name='period',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Empty: always.', null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Set when the bell times change, e.g. winter timings.', null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='valid_from',
            field=models.DateField(blank=True, help_text='First day the lesson runs. Empty: from the start of the year/term.', null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Last day the lesson runs. Empty: to the end of the year/term.', null=True),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='period_validity_ordered'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='timetable_entry_validity_ordered'),
        ),
    ]
