# Generated by Django 6.1.1 on 2026-10-01 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        ('students', '0002_enrollment_section_alter_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('in_review', 'In review'), ('returned', 'Sent back to the applicant'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='in_review', max_length=10)),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('token_hash', models.CharField(blank=True, help_text="SHA-256 of a public applicant's token.", max_length=64)),
                ('submitted_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.JSONField(blank=True, default=dict, help_text='What approval created, e.g. {"type": "hostel.allocation", "id": 7}.')),
                ('outcome_label', models.CharField(blank=True, max_length=255)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.student')),
            ],
            options={
                'db_table': 'applications_application',
                'ordering': ['-submitted_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Step approved'), ('completed', 'Approved (final)'), ('rejected', 'Rejected'), ('returned', 'Sent back'), ('resubmitted', 'Resubmitted'), ('withdrawn', 'Withdrawn')], max_length=12)),
                ('step', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('step_name', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'db_table': 'applications_event',
                'ordering': ['at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('admission', 'Admission'), ('leave', 'Staff leave'), ('scholarship', 'Scholarship'), ('hostel', 'Hostel bed'), ('transport', 'Transport'), ('event', 'Event participation'), ('certificate', 'Certificate'), ('general', 'General request')], max_length=12)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Admission only: accept submissions without an account.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('fields', models.JSONField(blank=True, default=list, help_text='Extra questions: [{name, label, type, required, choices}].')),
                ('certificate_title', models.CharField(blank=True, help_text='Certificate kind: the title printed, e.g. Character certificate.', max_length=150)),
                ('campus', models.ForeignKey(blank=True, help_text='Empty: open at every campus.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'applications_type',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.applicationtype'),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('name', models.CharField(help_text='e.g. Class teacher, Warden, Principal.', max_length=100)),
                ('permission', models.CharField(help_text='A permission code; its holders decide this step.', max_length=100)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='applications.applicationtype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'db_table': 'applications_step',
                'ordering': ['application_type_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=30)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('issued_on', models.DateField()),
                ('contents', models.JSONField(default=dict)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='applications.application')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.student')),
            ],
            options={
                'db_table': 'applications_certificate',
                'ordering': ['-issued_on', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='applicationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_application_type_code'),
        ),
        migrations.AddConstraint(
            model_name='applicationtype',
            constraint=models.CheckConstraint(condition=models.Q(('is_public', False), ('kind', 'admission'), _connector='OR'), name='application_type_public_admission_only'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['organization', 'status', 'campus'], name='application_organiz_4ebb6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_application_number'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('staff__isnull', False), ('student__isnull', False), _negated=True), name='application_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('application_type', 'sequence'), name='uniq_application_step'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_certificate_number'),
        ),
    ]
