# Generated by Django 6.1.1 on 2026-10-02 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('organizations', '0002_one_main_campus_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='applicationtype',
            name='application_type_public_admission_only',
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Admission and job only: accept submissions without an account.'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='kind',
            field=models.CharField(choices=[('admission', 'Admission'), ('leave', 'Staff leave'), ('scholarship', 'Scholarship'), ('hostel', 'Hostel bed'), ('transport', 'Transport'), ('event', 'Event participation'), ('certificate', 'Certificate'), ('job', 'Job application'), ('general', 'General request')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='applicationtype',
            constraint=models.CheckConstraint(condition=models.Q(('is_public', False), ('kind__in', ['admission', 'job']), _connector='OR'), name='application_type_public_kinds'),
        ),
    ]
