# Generated by Django 6.1.1 on 2026-10-02 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_job_kind'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('round', models.PositiveSmallIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('mode', models.CharField(choices=[('in_person', 'In person'), ('phone', 'Phone'), ('video', 'Video call')], default='in_person', max_length=10)),
                ('location', models.CharField(blank=True, help_text='A room, or the call link.', max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', "Candidate didn't come")], db_index=True, default='scheduled', max_length=10)),
                ('score', models.DecimalField(blank=True, decimal_places=1, help_text='0–10.', max_digits=4, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('hire', 'Hire'), ('hold', 'Hold'), ('reject', "Don't hire")], max_length=10)),
                ('feedback', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'careers_interview',
                'ordering': ['scheduled_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField()),
                ('contract_kind', models.CharField(choices=[('permanent', 'Permanent'), ('probation', 'Probation'), ('temporary', 'Temporary'), ('contract', 'Fixed-term contract'), ('part_time', 'Part-time')], max_length=20)),
                ('probation_ends_on', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, help_text='Empty: open-ended.', null=True)),
                ('salary_note', models.CharField(blank=True, help_text='What was offered; payroll sets the actual pay.', max_length=255)),
                ('terms', models.TextField(blank=True)),
                ('expires_on', models.DateField(blank=True, help_text='Last day to accept.', null=True)),
                ('status', models.CharField(choices=[('made', 'Made'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='made', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'careers_offer',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(choices=[('full_time', 'Full-time job'), ('part_time', 'Part-time job'), ('internship', 'Internship'), ('contract', 'Contract'), ('volunteer', 'Volunteer')], default='full_time', max_length=12)),
                ('description', models.TextField()),
                ('how_to_apply', models.TextField(blank=True)),
                ('apply_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('closes_on', models.DateField(blank=True, null=True)),
                ('audience', models.CharField(choices=[('students', 'Students'), ('alumni', 'Alumni'), ('both', 'Students and alumni')], default='both', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Listed'), ('rejected', 'Not approved'), ('closed', 'Closed')], db_index=True, default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'careers_posting',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('staff_type', models.CharField(choices=[('teaching', 'Teaching'), ('non_teaching', 'Non-teaching')], default='teaching', max_length=20)),
                ('contract_kind', models.CharField(choices=[('permanent', 'Permanent'), ('probation', 'Probation'), ('temporary', 'Temporary'), ('contract', 'Fixed-term contract'), ('part_time', 'Part-time')], default='probation', max_length=20)),
                ('openings', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.JSONField(blank=True, default=list, help_text='A list of requirement lines.')),
                ('min_experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary_range', models.CharField(blank=True, help_text='As advertised, e.g. 40,000–55,000.', max_length=100)),
                ('opens_on', models.DateField(blank=True, help_text='Set when it opens.', null=True)),
                ('closes_on', models.DateField(blank=True, help_text='Last day to apply.', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Listed on the public careers page.')),
                ('resume_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], db_index=True, default='draft', max_length=10)),
                ('hired_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'vacancies',
                'db_table': 'careers_vacancy',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Candidacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('screening_score', models.PositiveSmallIntegerField(blank=True, help_text='0–100.', null=True)),
                ('screening_note', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='candidacy', to='applications.application')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hired_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'candidacies',
                'db_table': 'careers_candidacy',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
