# Generated by Django 6.1.1 on 2026-10-02 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_one_main_campus_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_code', models.CharField(db_index=True, max_length=50, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9-]*[a-z0-9]$', 'Code may contain lowercase letters, digits and hyphens only.')])),
                ('organization_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('institute', 'Institute'), ('other', 'Other')], default='college', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('admin_email', models.EmailField(db_index=True, max_length=254)),
                ('admin_first_name', models.CharField(max_length=150)),
                ('admin_last_name', models.CharField(blank=True, max_length=150)),
                ('admin_phone', models.CharField(blank=True, max_length=32)),
                ('password_hash', models.CharField(max_length=128)),
                ('token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Waiting for email verification'), ('awaiting_approval', 'Verified, waiting for approval'), ('completed', 'Organization created'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
            ],
            options={
                'db_table': 'signup_request',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
