# Generated by Django 6.1.1 on 2026-09-23 09:31

from django.db import migrations, models

# Job titles that stopped being user types. They were labels only (access has
# always come from roles), so folding them into "staff" loses no access.
RETIRED_TYPES = ["accountant", "hr", "librarian"]


def fold_job_titles_into_staff(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(user_type__in=RETIRED_TYPES).update(user_type="staff")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        # One-way on purpose: which of the three a user used to be is not
        # recorded anywhere, so there is nothing to restore on reverse.
        migrations.RunPython(fold_job_titles_into_staff, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('administrator', 'Administrator')], db_index=True, default='staff', help_text='What this person is. Access rights come from roles, not this field.', max_length=20),
        ),
    ]
