# Generated by Django 6.1.1 on 2026-10-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_broad_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('administrator', 'Administrator'), ('alumni', 'Alumni')], db_index=True, default='staff', help_text='What this person is. Access rights come from roles, not this field.', max_length=20),
        ),
    ]
