# Generated by Django 6.1.1 on 2026-09-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Academic placement. Empty until the student is placed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('moved', 'Moved to another section')], db_index=True, default='active', max_length=20),
        ),
    ]
