# Generated by Django 6.1.1 on 2026-10-01 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_invoice_source'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        ('students', '0002_enrollment_section_alter_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Boys / men only'), ('female', 'Girls / women only'), ('mixed', 'Anyone')], default='mixed', help_text='Who may be allocated a bed here.', max_length=6)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('warden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staffmember')),
            ],
            options={
                'db_table': 'hostel_building',
                'ordering': ['campus_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.SmallIntegerField(help_text='0 = ground floor; negative for basements.')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floors', to='hostel.building')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'hostel_floor',
                'ordering': ['building_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hostel.building')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hostel.floor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'hostel_room',
                'ordering': ['building_id', 'floor_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('maintenance', 'Repairs and maintenance'), ('cleanliness', 'Cleanliness'), ('food', 'Food / mess'), ('security', 'Safety and security'), ('roommate', 'Roommates and conduct'), ('other', 'Other')], default='other', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'Being handled'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=12)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staffmember')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='hostel.building')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='hostel.hostelroom')),
            ],
            options={
                'db_table': 'hostel_complaint',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', models.CharField(help_text='A, B, 1, 2…', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Off = out of service; no new allocations.')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beds', to='hostel.hostelroom')),
            ],
            options={
                'db_table': 'hostel_bed',
                'ordering': ['room_id', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('fee_per_term', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fee_category', models.ForeignKey(blank=True, help_text="The invoice line's category. Needed to bill.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.feecategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'hostel_room_type',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hostel.roomtype'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved (not yet checked in)'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cancelled', 'Cancelled before check-in')], db_index=True, default='reserved', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('end_note', models.CharField(blank=True, help_text='Why it ended or was cancelled.', max_length=255)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.student')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostel.bed')),
            ],
            options={
                'db_table': 'hostel_allocation',
                'ordering': ['-start_date', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('staff__isnull', True), ('student__isnull', False)), models.Q(('staff__isnull', False), ('student__isnull', True)), _connector='OR'), name='hostel_allocation_exactly_one_occupant'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='hostel_allocation_dates_in_order'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['reserved', 'checked_in'])), fields=('bed',), name='uniq_hostel_bed_holder'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['reserved', 'checked_in'])), fields=('student',), name='uniq_hostel_student_bed'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status__in', ['reserved', 'checked_in'])), fields=('staff',), name='uniq_hostel_staff_bed')],
            },
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_hostel_building_code'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('building', 'number'), name='uniq_hostel_floor'),
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('room', 'label'), name='uniq_hostel_bed'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_hostel_room_type_code'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.CheckConstraint(condition=models.Q(('fee_per_term__gte', 0)), name='hostel_room_type_fee_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('building', 'number'), name='uniq_hostel_room'),
        ),
    ]
