# Generated by Django 6.1.1 on 2026-09-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('students', '0002_enrollment_section_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassignment',
            name='periods_per_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many lessons a week. The timetable generator fills up to this.', null=True),
        ),
        migrations.CreateModel(
            name='StudentElective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electives', to='students.enrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_electives', to='organizations.organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_choices', to='academics.subject')),
            ],
            options={
                'db_table': 'academics_student_elective',
                'ordering': ['enrollment', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'subject'), name='uniq_student_elective')],
            },
        ),
    ]
