# Generated by Django 6.1.1 on 2026-09-23 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_dated_electives_assignment_roles'),
        ('organizations', '0002_one_main_campus_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('holiday', 'Holiday'), ('closure', 'Closure'), ('exam', 'Exam'), ('event', 'Event'), ('makeup_day', 'Make-up day')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Inclusive. The same as start_date for one day.')),
                ('level', models.PositiveSmallIntegerField(blank=True, help_text='With a program: only this grade or semester.', null=True)),
                ('suspends_classes', models.BooleanField(help_text="Regular lessons don't take place.")),
                ('runs_timetable_of', models.PositiveSmallIntegerField(blank=True, help_text="Make-up day: run this weekday's timetable (1 = Monday … 7 = Sunday).", null=True)),
                ('campus', models.ForeignKey(blank=True, help_text='Empty: every campus.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_events', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('program', models.ForeignKey(blank=True, help_text='Empty: every program.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_events', to='academics.program')),
            ],
            options={
                'db_table': 'academics_calendar_event',
                'ordering': ['start_date', 'pk'],
                'indexes': [models.Index(fields=['organization', 'start_date', 'end_date'], name='academics_c_organiz_705e0e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='calendar_event_dates_ordered'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'makeup_day'), ('runs_timetable_of__gte', 1), ('runs_timetable_of__lte', 7), ('suspends_classes', False)), models.Q(models.Q(('kind', 'makeup_day'), _negated=True), ('runs_timetable_of__isnull', True)), _connector='OR'), name='calendar_makeup_day_names_a_weekday'), models.CheckConstraint(condition=models.Q(('level__isnull', True), ('program__isnull', False), _connector='OR'), name='calendar_level_needs_program')],
            },
        ),
    ]
