# Generated by Django 6.1.1 on 2026-09-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_calendar_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='attendance_mode',
            field=models.CharField(choices=[('daily', 'Once a day, by the class teacher'), ('lesson', 'In every lesson, by its teacher')], default='daily', help_text='Schools usually take one roll call a day; colleges take it every lesson.', max_length=10),
        ),
    ]
