# Generated by Django 6.1.1 on 2026-10-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('fees', 'Tuition and fees'), ('hostel', 'Hostel'), ('transport', 'Transport')], db_index=True, default='fees', max_length=10),
        ),
    ]
