# Generated by Django 6.1.1 on 2026-10-01 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_invoice_source'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        ('students', '0002_enrollment_section_alter_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('assistant', 'Assistant / conductor')], default='driver', max_length=10)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_category', models.CharField(blank=True, help_text='e.g. B, C, C1', max_length=20)),
                ('license_expires_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
            ],
            options={
                'db_table': 'transport_driver',
                'ordering': ['staff__first_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('fee_per_term', models.DecimalField(decimal_places=2, default=0, help_text='Per rider, per term; a stop can charge its own instead.', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_assisted', to='transport.driver')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_driven', to='transport.driver')),
                ('fee_category', models.ForeignKey(blank=True, help_text="The invoice line's category. Needed to bill.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.feecategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'transport_route',
                'ordering': ['campus_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField(help_text='Order along the morning run, from 1.')),
                ('name', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fee_per_term', models.DecimalField(blank=True, decimal_places=2, help_text="Overrides the route's fee for riders boarding here.", max_digits=10, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='transport.route')),
            ],
            options={
                'db_table': 'transport_stop',
                'ordering': ['route_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('direction', models.CharField(choices=[('both', 'Both ways'), ('pickup', 'Morning pickup only'), ('drop', 'Afternoon drop only')], default='both', max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=255)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.student')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='transport.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='transport.stop')),
            ],
            options={
                'db_table': 'transport_assignment',
                'ordering': ['-start_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('direction', models.CharField(choices=[('pickup', 'Morning pickup'), ('drop', 'Afternoon drop')], max_length=6)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], db_index=True, default='open', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transport.driver')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transport.driver')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transport.route')),
            ],
            options={
                'db_table': 'transport_trip',
                'ordering': ['-date', 'route_id', 'direction'],
            },
        ),
        migrations.CreateModel(
            name='TripRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('boarded', 'Boarded'), ('absent', 'Absent')], max_length=8)),
                ('at', models.TimeField(blank=True, help_text='When they got on (or off, on a drop).', null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='transport.assignment')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='transport.trip')),
            ],
            options={
                'db_table': 'transport_trip_record',
                'ordering': ['trip_id', 'assignment__stop__sequence', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('registration_number', models.CharField(help_text='As on the bluebook, e.g. Ba 2 Kha 1234.', max_length=30)),
                ('name', models.CharField(help_text='What everyone calls it, e.g. Bus 3.', max_length=50)),
                ('kind', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('van', 'Van'), ('car', 'Car / jeep'), ('other', 'Other')], default='bus', max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(help_text='Seats for riders.')),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'transport_vehicle',
                'ordering': ['campus_id', 'name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transport.vehicle'),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='transport.vehicle'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('service', 'Regular service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('tyres', 'Tyres'), ('other', 'Other')], max_length=10)),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('next_due_on', models.DateField(blank=True, null=True)),
                ('next_due_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance', to='transport.vehicle')),
            ],
            options={
                'db_table': 'transport_maintenance',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField()),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='transport.vehicle')),
            ],
            options={
                'db_table': 'transport_fuel_log',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('bluebook', 'Registration (bluebook)'), ('insurance', 'Insurance'), ('route_permit', 'Route permit'), ('pollution', 'Pollution test'), ('fitness', 'Fitness certificate'), ('tax', 'Road tax'), ('other', 'Other')], max_length=14)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, db_index=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transport.vehicle')),
            ],
            options={
                'db_table': 'transport_vehicle_document',
                'ordering': ['vehicle_id', 'kind', '-expires_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('staff',), name='uniq_transport_driver_staff'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('route', 'sequence'), name='uniq_transport_stop_seq'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.CheckConstraint(condition=models.Q(('fee_per_term__isnull', True), ('fee_per_term__gte', 0), _connector='OR'), name='transport_stop_fee_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('staff__isnull', True), ('student__isnull', False)), models.Q(('staff__isnull', False), ('student__isnull', True)), _connector='OR'), name='transport_assignment_exactly_one_rider'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='transport_assignment_dates_in_order'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('end_date__isnull', True)), fields=('student',), name='uniq_transport_student_open'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('end_date__isnull', True)), fields=('staff',), name='uniq_transport_staff_open'),
        ),
        migrations.AddConstraint(
            model_name='triprecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('trip', 'assignment'), name='uniq_transport_trip_record'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'registration_number'), name='uniq_transport_vehicle_registration'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='transport_vehicle_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('route', 'date', 'direction'), name='uniq_transport_trip'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_transport_route_code'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('fee_per_term__gte', 0)), name='transport_route_fee_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='maintenance',
            constraint=models.CheckConstraint(condition=models.Q(('cost__isnull', True), ('cost__gte', 0), _connector='OR'), name='transport_maintenance_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='fuellog',
            constraint=models.CheckConstraint(condition=models.Q(('litres__gt', 0)), name='transport_fuel_litres_positive'),
        ),
        migrations.AddConstraint(
            model_name='fuellog',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='transport_fuel_cost_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='vehicledocument',
            constraint=models.CheckConstraint(condition=models.Q(('issued_on__isnull', True), ('expires_on__isnull', True), ('expires_on__gte', models.F('issued_on')), _connector='OR'), name='transport_document_dates_in_order'),
        ),
    ]
