# Generated by Django 6.1.1 on 2026-09-27 05:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_program_attendance_mode'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        ('students', '0002_enrollment_section_alter_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Being set up'), ('scheduled', 'Scheduled'), ('published', 'Results published')], db_index=True, default='draft', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('min_attendance_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Students below this attendance get their admit card withheld.', max_digits=5, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Printed on every admit card.')),
                ('on_transcript', models.BooleanField(default=False, help_text="Include this exam's own result on transcripts.")),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.academicyear')),
                ('calendar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.calendarevent')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.program')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='academics.term')),
            ],
            options={
                'db_table': 'examinations_exam',
                'ordering': ['-start_date', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text="Seats for this exam. Empty: the room's capacity.", null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='examinations.exam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_rooms', to='organizations.organization')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_uses', to='academics.room')),
            ],
            options={
                'db_table': 'examinations_exam_room',
                'ordering': ['exam_id', 'room__code'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('credit_hours', models.DecimalField(blank=True, decimal_places=1, help_text="Weight in the GPA. Empty: the subject's credit hours, or 1.", max_digits=4, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='examinations.exam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='organizations.organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subjects', to='academics.subject')),
            ],
            options={
                'db_table': 'examinations_exam_subject',
                'ordering': ['exam_id', 'level', 'date', 'start_time', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='ExamComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('internal', 'Internal assessment'), ('viva', 'Viva'), ('project', 'Project'), ('other', 'Other')], default='theory', max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('full_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pass_marks', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_components', to='organizations.organization')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='examinations.examsubject')),
            ],
            options={
                'db_table': 'examinations_exam_component',
                'ordering': ['exam_subject_id', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'examinations_exam_type',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='examinations.examtype'),
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('max_grade_point', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=4)),
                ('require_all_subjects_pass', models.BooleanField(default=True, help_text='One failed subject fails the whole result.')),
                ('overall_pass_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='If set, an overall percentage below this fails the result too.', max_digits=5, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('program', models.ForeignKey(blank=True, help_text="Empty: the organization's default scale.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='academics.program')),
            ],
            options={
                'db_table': 'examinations_grade_scale',
                'ordering': ['program__name', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('letter', models.CharField(max_length=10)),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('is_pass', models.BooleanField(default=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='examinations.gradescale')),
            ],
            options={
                'db_table': 'examinations_grade_band',
                'ordering': ['scale_id', '-min_percentage'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='examinations.gradescale'),
        ),
        migrations.CreateModel(
            name='DivisionBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(max_length=50)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='examinations.gradescale')),
            ],
            options={
                'db_table': 'examinations_division_band',
                'ordering': ['scale_id', '-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Invigilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_chief', models.BooleanField(default=False)),
                ('exam_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilations', to='examinations.examroom')),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilations', to='examinations.examsubject')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilations', to='organizations.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invigilations', to='staff.staffmember')),
            ],
            options={
                'db_table': 'examinations_invigilation',
                'ordering': ['exam_subject_id', 'exam_room_id', '-is_chief', 'staff_id'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('exempt', 'Exempt'), ('withheld', 'Withheld')], default='present', max_length=10)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='examinations.examcomponent')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='students.enrollment')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='organizations.organization')),
            ],
            options={
                'db_table': 'examinations_mark',
                'ordering': ['sheet_id', 'enrollment_id', 'component_id'],
            },
        ),
        migrations.CreateModel(
            name='MarkCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('exempt', 'Exempt'), ('withheld', 'Withheld')], max_length=10)),
                ('old_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('exempt', 'Exempt'), ('withheld', 'Withheld')], max_length=10)),
                ('new_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='examinations.mark')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_corrections', to='organizations.organization')),
            ],
            options={
                'db_table': 'examinations_mark_correction',
                'ordering': ['mark_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Being entered'), ('submitted', 'Submitted'), ('verified', 'Verified')], db_index=True, default='open', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, help_text='Why the office sent it back.', max_length=255)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='examinations.examsubject')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_sheets', to='organizations.organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_sheets', to='academics.section')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'examinations_mark_sheet',
                'ordering': ['exam_subject_id', 'section_id'],
            },
        ),
        migrations.AddField(
            model_name='mark',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='examinations.marksheet'),
        ),
        migrations.CreateModel(
            name='ResultPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('on_transcript', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_plans', to='academics.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_plans', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grade_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_plans', to='examinations.gradescale')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_plans', to='academics.program')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_plans', to='academics.term')),
            ],
            options={
                'db_table': 'examinations_result_plan',
                'ordering': ['-academic_year__start_date', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_obtained', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('total_full', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('letter', models.CharField(blank=True, max_length=10)),
                ('division', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('withheld', 'Withheld'), ('incomplete', 'Marks missing'), ('exempt', 'Exempt')], default='incomplete', max_length=12)),
                ('rank_in_section', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_in_level', models.PositiveIntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=500)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='students.enrollment')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.exam')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='organizations.organization')),
                ('remark_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_results', to='students.student')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examinations.resultplan')),
            ],
            options={
                'db_table': 'examinations_result',
                'ordering': ['section_id', '-percentage', 'student__first_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ResultPlanExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Percent of the term result.', max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='examinations.exam')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='examinations.resultplan')),
            ],
            options={
                'db_table': 'examinations_result_plan_exam',
                'ordering': ['plan_id', 'exam__start_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_number', models.PositiveIntegerField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_seats', to='students.enrollment')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='examinations.exam')),
                ('exam_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='examinations.examroom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='organizations.organization')),
            ],
            options={
                'db_table': 'examinations_seat_allocation',
                'ordering': ['exam_room_id', 'seat_number'],
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_hours', models.DecimalField(decimal_places=1, default=Decimal('1'), max_digits=4)),
                ('obtained', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('full', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('letter', models.CharField(blank=True, max_length=10)),
                ('grade_point', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('withheld', 'Withheld'), ('incomplete', 'Marks missing'), ('exempt', 'Exempt')], default='pass', max_length=12)),
                ('absent', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=list, help_text='Components (or, for a plan, the exams) that made this line.')),
                ('exam_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='examinations.examsubject')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='examinations.result')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.subject')),
            ],
            options={
                'db_table': 'examinations_subject_result',
                'ordering': ['result_id', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('withheld', 'Withheld')], default='issued', max_length=10)),
                ('withheld_reason', models.CharField(blank=True, max_length=255)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admit_cards', to='students.enrollment')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admit_cards', to='students.student')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='examinations.exam')),
            ],
            options={
                'db_table': 'examinations_admit_card',
                'ordering': ['exam_id', 'card_number'],
                'constraints': [models.UniqueConstraint(fields=('exam', 'enrollment'), name='uniq_admit_card_per_student'), models.UniqueConstraint(fields=('exam', 'card_number'), name='uniq_admit_card_number')],
            },
        ),
        migrations.AddConstraint(
            model_name='examroom',
            constraint=models.UniqueConstraint(fields=('exam', 'room'), name='uniq_exam_room'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.UniqueConstraint(fields=('exam', 'level', 'subject'), name='uniq_exam_subject'),
        ),
        migrations.AddConstraint(
            model_name='examsubject',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('end_time__gt', models.F('start_time')), _connector='OR'), name='exam_subject_times_ordered'),
        ),
        migrations.AddConstraint(
            model_name='examcomponent',
            constraint=models.UniqueConstraint(fields=('exam_subject', 'name'), name='uniq_exam_component_name'),
        ),
        migrations.AddConstraint(
            model_name='examcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('full_marks__gt', 0)), name='exam_component_full_positive'),
        ),
        migrations.AddConstraint(
            model_name='examcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('pass_marks__gte', 0), ('pass_marks__lte', models.F('full_marks'))), name='exam_component_pass_in_range'),
        ),
        migrations.AddConstraint(
            model_name='examtype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_exam_type_code'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('program__isnull', False)), fields=('organization', 'program'), name='uniq_grade_scale_per_program'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('program__isnull', True)), fields=('organization',), name='uniq_default_grade_scale'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(fields=('scale', 'min_percentage'), name='uniq_grade_band_min'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.CheckConstraint(condition=models.Q(('min_percentage__gte', 0), ('min_percentage__lte', 100)), name='grade_band_percentage_range'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['organization', 'academic_year', 'campus'], name='examination_organiz_78f168_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('campus', 'academic_year', 'name'), name='uniq_exam_name'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='exam_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='divisionband',
            constraint=models.UniqueConstraint(fields=('scale', 'min_percentage'), name='uniq_division_band_min'),
        ),
        migrations.AddConstraint(
            model_name='invigilation',
            constraint=models.UniqueConstraint(fields=('exam_subject', 'exam_room', 'staff'), name='uniq_invigilation'),
        ),
        migrations.AddConstraint(
            model_name='marksheet',
            constraint=models.UniqueConstraint(fields=('exam_subject', 'section'), name='uniq_mark_sheet'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('component', 'enrollment'), name='uniq_mark'),
        ),
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('marks__gte', 0), ('marks__isnull', False), ('status', 'present')), models.Q(models.Q(('status', 'present'), _negated=True), ('marks__isnull', True)), _connector='OR'), name='mark_value_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='resultplan',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('campus', 'academic_year', 'name'), name='uniq_result_plan_name'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'exam'], name='examination_student_cc2753_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'plan'], name='examination_student_54a050_idx'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('exam__isnull', False), ('plan__isnull', True)), models.Q(('exam__isnull', True), ('plan__isnull', False)), _connector='OR'), name='result_exam_xor_plan'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(condition=models.Q(('exam__isnull', False)), fields=('exam', 'enrollment'), name='uniq_exam_result'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(condition=models.Q(('plan__isnull', False)), fields=('plan', 'enrollment'), name='uniq_plan_result'),
        ),
        migrations.AddConstraint(
            model_name='resultplanexam',
            constraint=models.UniqueConstraint(fields=('plan', 'exam'), name='uniq_plan_exam'),
        ),
        migrations.AddConstraint(
            model_name='resultplanexam',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0), ('weight__lte', 100)), name='plan_exam_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='seatallocation',
            constraint=models.UniqueConstraint(fields=('exam', 'enrollment'), name='uniq_seat_per_student'),
        ),
        migrations.AddConstraint(
            model_name='seatallocation',
            constraint=models.UniqueConstraint(fields=('exam_room', 'seat_number'), name='uniq_seat_number'),
        ),
        migrations.AddConstraint(
            model_name='subjectresult',
            constraint=models.UniqueConstraint(fields=('result', 'subject'), name='uniq_subject_result'),
        ),
    ]
