# Generated by Django 6.1.1 on 2026-09-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partial', 'Partly received'), ('received', 'Fully received'), ('closed', 'Closed short (rest will not arrive)'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10),
        ),
    ]
