# Generated by Django 6.1.1 on 2026-09-30 14:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('earning', 'Earning (allowance)'), ('deduction', 'Deduction')], max_length=20)),
                ('calculation', models.CharField(choices=[('fixed', 'Fixed amount a month'), ('percent_of_basic', 'Percentage of basic')], default='fixed', max_length=20)),
                ('is_taxable', models.BooleanField(default=True, help_text='Earnings: counts as taxable income.')),
                ('is_pre_tax', models.BooleanField(default=False, help_text='Deductions: taken before tax (provident fund, CIT, SSF).')),
                ('prorate_for_absence', models.BooleanField(default=True, help_text='Earnings: reduced for unpaid days, like basic.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive components are left off new payslips.')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'payroll_component',
                'ordering': ['kind', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Baisakh 2083'.", max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(help_text='Inclusive.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(blank=True, help_text='Picks the tax scheme.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.fiscalyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_run',
                'ordering': ['-period_start', 'campus_id', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('absence_basis', models.CharField(choices=[('marked', 'Only days marked absent'), ('unrecorded', 'Any past working day without attendance')], default='marked', help_text="'unrecorded' suits campuses where everyone punches in; 'marked' where they don't.", max_length=20)),
                ('deduct_half_days', models.BooleanField(default=False, help_text="A half day costs half a day's pay.")),
                ('days_basis', models.CharField(choices=[('working', 'Working days in the period'), ('calendar', 'Calendar days in the period')], default='working', help_text="A day's pay is the monthly amount divided by these.", max_length=20)),
                ('overtime_enabled', models.BooleanField(default=True)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('overtime_min_minutes', models.PositiveSmallIntegerField(default=30, help_text="Extra time on a day below this isn't counted.")),
                ('default_day_minutes', models.PositiveSmallIntegerField(default=480, help_text='Length of a working day for staff with no work schedule.')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'payroll settings',
                'db_table': 'payroll_settings',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basis_days', models.PositiveSmallIntegerField(help_text="A day's pay is the monthly amount / this.")),
                ('working_days', models.DecimalField(decimal_places=1, help_text='Expected while employed.', max_digits=5)),
                ('worked_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('paid_leave_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('unpaid_leave_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('absent_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('not_employed_days', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=5)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes_override', models.PositiveIntegerField(blank=True, help_text='Set by hand; used instead of the count.', null=True)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="This period's, after pre-tax deductions.", max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Including tax.', max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Day-by-day working-out and warnings.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
            ],
            options={
                'db_table': 'payroll_payslip',
                'ordering': ['run_id', 'staff__first_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=200)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_taxable', models.BooleanField(default=True, help_text='Earnings: counts as taxable income.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('corrects', models.ForeignKey(blank=True, help_text='The approved payslip this puts right, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='payroll.payslip')),
                ('payslip', models.ForeignKey(blank=True, help_text='Where it was paid (or recovered).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='payroll.payslip')),
            ],
            options={
                'db_table': 'payroll_adjustment',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('source', models.CharField(choices=[('basic', 'Basic salary'), ('component', 'Salary component'), ('unpaid_days', 'Unpaid days'), ('overtime', 'Overtime'), ('adjustment', 'Adjustment'), ('tax', 'Income tax')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_pre_tax', models.BooleanField(default=False)),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.payrolladjustment')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.paycomponent')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payslip')),
            ],
            options={
                'db_table': 'payroll_payslip_line',
                'ordering': ['payslip_id', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('basic', models.DecimalField(decimal_places=2, help_text='Monthly basic salary.', max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'payroll_salary_structure',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='An amount, or a percentage for percent-of-basic components.', max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.paycomponent')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.salarystructure')),
            ],
            options={
                'db_table': 'payroll_salary_structure_line',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic', models.DecimalField(blank=True, decimal_places=2, help_text="This person's own basic. Empty: the structure's.", max_digits=12, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Inclusive. Empty: until replaced.', null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='payroll.salarystructure')),
            ],
            options={
                'verbose_name_plural': 'staff salaries',
                'db_table': 'payroll_staff_salary',
                'ordering': ['staff_id', '-effective_from', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.staffsalary'),
        ),
        migrations.CreateModel(
            name='StaffSalaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.paycomponent')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.staffsalary')),
            ],
            options={
                'db_table': 'payroll_staff_salary_line',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TaxScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('tax_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married / couple')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('female_rebate_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Taken off the tax of women employees.', max_digits=5)),
                ('pre_tax_cap_annual', models.DecimalField(blank=True, decimal_places=2, help_text='Pre-tax deductions count up to this much a year. Empty: no cap.', max_digits=12, null=True)),
                ('pre_tax_cap_fraction', models.DecimalField(blank=True, decimal_places=4, help_text='…and up to this share of taxable income (e.g. 0.3333). Empty: no cap.', max_digits=5, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.fiscalyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'payroll_tax_scheme',
                'ordering': ['-fiscal_year__start_date', 'tax_status', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='payroll.taxscheme'),
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('upto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='payroll.taxscheme')),
            ],
            options={
                'db_table': 'payroll_tax_slab',
                'ordering': ['scheme_id', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='paycomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_payroll_component'),
        ),
        migrations.AddConstraint(
            model_name='paycomponent',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'deduction'), ('is_pre_tax', False), _connector='OR'), name='payroll_pre_tax_is_a_deduction'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['organization', 'period_start'], name='payroll_run_organiz_b03fcd_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='payroll_run_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization',), name='uniq_payroll_settings'),
        ),
        migrations.AddConstraint(
            model_name='payrollsettings',
            constraint=models.CheckConstraint(condition=models.Q(('overtime_multiplier__gt', 0)), name='payroll_overtime_multiplier_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrolladjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payroll_adjustment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payroll_line_amount_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_salary_structure'),
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.CheckConstraint(condition=models.Q(('basic__gte', 0)), name='payroll_structure_basic_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureline',
            constraint=models.UniqueConstraint(fields=('structure', 'component'), name='uniq_structure_component'),
        ),
        migrations.AddConstraint(
            model_name='salarystructureline',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='payroll_structure_line_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='staffsalary',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('staff',), name='uniq_open_staff_salary'),
        ),
        migrations.AddConstraint(
            model_name='staffsalary',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='payroll_staff_salary_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='staffsalary',
            constraint=models.CheckConstraint(condition=models.Q(('basic__isnull', True), ('basic__gte', 0), _connector='OR'), name='payroll_staff_basic_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='staffsalaryline',
            constraint=models.UniqueConstraint(fields=('salary', 'component'), name='uniq_staff_salary_component'),
        ),
        migrations.AddConstraint(
            model_name='staffsalaryline',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='payroll_staff_line_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='taxscheme',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('fiscal_year', 'tax_status'), name='uniq_tax_scheme_per_year_status'),
        ),
        migrations.AddConstraint(
            model_name='taxscheme',
            constraint=models.CheckConstraint(condition=models.Q(('female_rebate_percent__gte', 0), ('female_rebate_percent__lte', 100)), name='payroll_rebate_is_a_percentage'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('run', 'staff'), name='uniq_payslip_per_run'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_payslip_number'),
        ),
        migrations.AddConstraint(
            model_name='taxslab',
            constraint=models.UniqueConstraint(fields=('scheme', 'sequence'), name='uniq_tax_slab_sequence'),
        ),
        migrations.AddConstraint(
            model_name='taxslab',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='payroll_slab_rate_percentage'),
        ),
    ]
