# Generated by Django 6.1.1 on 2026-09-23 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_main', True)), fields=('organization',), name='uniq_main_campus_per_organization'),
        ),
    ]
