# Generated by Django 6.1.1 on 2026-09-24 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_program_attendance_mode'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        ('students', '0002_enrollment_section_alter_enrollment_status'),
        ('timetable', '0003_validity_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('zkteco', 'ZKTeco (push protocol)'), ('generic', 'Generic (device API)')], max_length=20)),
                ('serial_number', models.CharField(help_text='As printed on the device.', max_length=64)),
                ('key_hash', models.CharField(blank=True, help_text="Generic devices' API key.", max_length=128)),
                ('key_prefix', models.CharField(blank=True, max_length=12)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='If set, only these addresses may send as this device. Recommended for ZKTeco, whose protocol identifies a device by its serial number alone.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'attendance_device',
                'ordering': ['campus', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('leave', 'On leave'), ('medical_leave', 'Medical leave'), ('on_duty', 'On duty')], max_length=20)),
                ('source', models.CharField(choices=[('teacher', 'Teacher'), ('manual', 'Office'), ('qr', 'QR scan'), ('biometric', 'Biometric device'), ('api', 'API')], default='teacher', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text="When it was taken, by the client's clock (offline marking).")),
                ('client_key', models.CharField(blank=True, help_text='Chosen by the app for each record, so a retried sync never duplicates it.', max_length=64)),
                ('device_id', models.CharField(blank=True, help_text='The phone a QR scan came from.', max_length=128)),
                ('enrollment', models.ForeignKey(help_text="The student's stay in the class on that date.", on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='students.enrollment')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Who actually marked it. Empty for a device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='organizations.organization')),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['session', 'enrollment__student__first_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('leave', 'On leave'), ('medical_leave', 'Medical leave'), ('on_duty', 'On duty')], max_length=20)),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('leave', 'On leave'), ('medical_leave', 'Medical leave'), ('on_duty', 'On duty')], max_length=20)),
                ('reason', models.CharField(max_length=255)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='attendance.attendancerecord')),
            ],
            options={
                'db_table': 'attendance_correction',
                'ordering': ['corrected_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('daily', 'Daily roll call'), ('lesson', 'Lesson')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted')], default='open', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='organizations.organization')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='academics.section')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, help_text="Who takes it that day: the lesson's teacher after substitutions, or the class teacher for a daily roll call.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('timetable_entry', models.ForeignKey(blank=True, help_text='The lesson, for lesson sessions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='timetable.timetableentry')),
            ],
            options={
                'db_table': 'attendance_session',
                'ordering': ['-date', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.CreateModel(
            name='BiometricIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin', models.CharField(max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staff.staffmember')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'biometric identities',
                'db_table': 'attendance_biometric_identity',
                'ordering': ['pin'],
            },
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=32)),
                ('punched_at', models.DateTimeField()),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('source', models.CharField(choices=[('teacher', 'Teacher'), ('manual', 'Office'), ('qr', 'QR scan'), ('biometric', 'Biometric device'), ('api', 'API')], max_length=20)),
                ('verify', models.CharField(blank=True, help_text='fingerprint, face, card …', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('dedupe_key', models.CharField(help_text='The same event sent twice has the same key.', max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='punches', to='attendance.attendancedevice')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'punches',
                'db_table': 'attendance_punch',
                'ordering': ['-punched_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('half_day', 'Half day'), ('absent', 'Absent'), ('leave', 'On leave'), ('on_duty', 'On duty')], max_length=20)),
                ('first_in', models.DateTimeField(blank=True, null=True)),
                ('last_out', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_override', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
            ],
            options={
                'db_table': 'attendance_staff_day',
                'ordering': ['-date', 'staff__first_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_minutes', models.PositiveSmallIntegerField(default=10, help_text='Arriving later than this after the start is late.')),
                ('half_day_minutes', models.PositiveSmallIntegerField(default=240, help_text='Working less than this, with a check-out, is a half day.')),
                ('weekdays', models.JSONField(default=list, help_text='Working days, ISO numbers: 1 = Monday … 7 = Sunday.')),
                ('is_default', models.BooleanField(default=False, help_text="Used for the campus's staff who have no schedule of their own.")),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'attendance_work_schedule',
                'ordering': ['campus', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StaffWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='staff.staffmember')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='attendance.workschedule')),
            ],
            options={
                'db_table': 'attendance_staff_work_schedule',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancedevice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('serial_number',), name='uniq_device_serial'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['organization', 'date'], name='attendance__organiz_ef3c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['section', 'date'], name='attendance__section_414b05_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'daily')), fields=('section', 'date'), name='uniq_daily_session'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'lesson')), fields=('timetable_entry', 'date'), name='uniq_lesson_session'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'lesson'), ('timetable_entry__isnull', False)), models.Q(('kind', 'daily'), ('timetable_entry__isnull', True)), _connector='OR'), name='session_entry_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'submitted'), ('submitted_at__isnull', False)), models.Q(('status', 'open'), ('submitted_at__isnull', True)), _connector='OR'), name='session_submitted_at_matches_status'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['organization', 'status'], name='attendance__organiz_e2dc4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'enrollment'), name='uniq_attendance_record'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key', ''), _negated=True), fields=('organization', 'client_key'), name='uniq_attendance_client_key'),
        ),
        migrations.AddConstraint(
            model_name='biometricidentity',
            constraint=models.UniqueConstraint(fields=('organization', 'pin'), name='uniq_biometric_pin'),
        ),
        migrations.AddConstraint(
            model_name='biometricidentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('staff__isnull', False), ('student__isnull', True)), models.Q(('staff__isnull', True), ('student__isnull', False)), _connector='OR'), name='biometric_identity_is_one_person'),
        ),
        migrations.AddIndex(
            model_name='punch',
            index=models.Index(fields=['staff', 'punched_at'], name='attendance__staff_i_640098_idx'),
        ),
        migrations.AddIndex(
            model_name='punch',
            index=models.Index(fields=['organization', 'pin'], name='attendance__organiz_da3895_idx'),
        ),
        migrations.AddConstraint(
            model_name='punch',
            constraint=models.UniqueConstraint(fields=('organization', 'dedupe_key'), name='uniq_punch'),
        ),
        migrations.AddIndex(
            model_name='staffattendanceday',
            index=models.Index(fields=['organization', 'date'], name='attendance__organiz_6d504a_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffattendanceday',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='uniq_staff_day'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('campus',), name='uniq_default_work_schedule'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='work_schedule_times_ordered'),
        ),
    ]
