# Generated by Django 6.1.1 on 2026-10-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('students', 'Students'), ('parents', 'Parents'), ('staff', 'Staff'), ('alumni', 'Alumni')], db_index=True, default='all', max_length=10),
        ),
    ]
