# Generated by Django 6.1.1 on 2026-09-23 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_one_main_campus_per_organization'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('application_number', models.CharField(max_length=32)),
                ('applied_on', models.DateField(default=django.utils.timezone.localdate)),
                ('applying_for', models.CharField(blank=True, help_text='Program or grade applied for. Becomes a link to a program in Phase 3.', max_length=200)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('guardian_first_name', models.CharField(blank=True, max_length=150)),
                ('guardian_last_name', models.CharField(blank=True, max_length=150)),
                ('guardian_relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], max_length=20)),
                ('guardian_phone', models.CharField(blank=True, max_length=32)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('enrolled', 'Enrolled')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='organizations.campus')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('student', models.OneToOneField(blank=True, help_text='The student record created on enrollment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission', to='students.student')),
            ],
            options={
                'db_table': 'admissions_admission',
                'ordering': ['-applied_on', '-pk'],
                'indexes': [models.Index(fields=['organization', 'status'], name='admissions__organiz_7c2804_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'application_number'), name='uniq_application_number_per_organization'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'enrolled'), ('student__isnull', False)), models.Q(models.Q(('status', 'enrolled'), _negated=True), ('student__isnull', True)), _connector='OR'), name='admission_student_matches_status')],
            },
        ),
    ]
