# Generated by Django 6.1.1 on 2026-09-23 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_one_main_campus_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('employee_number', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('staff_type', models.CharField(choices=[('teaching', 'Teaching'), ('non_teaching', 'Non-teaching')], db_index=True, default='teaching', max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('left', 'Left')], db_index=True, default='active', max_length=20)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('left_on', models.DateField(blank=True, null=True)),
                ('campus', models.ForeignKey(help_text='Main place of work.', on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('user', models.OneToOneField(blank=True, help_text='Login account, if the staff member uses the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff member',
                'db_table': 'staff_member',
                'ordering': ['first_name', 'last_name', 'pk'],
                'indexes': [models.Index(fields=['organization', 'status'], name='staff_membe_organiz_5829d7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'employee_number'), name='uniq_employee_number_per_organization'), models.CheckConstraint(condition=models.Q(models.Q(('left_on__isnull', False), ('status', 'left')), models.Q(models.Q(('status', 'left'), _negated=True), ('left_on__isnull', True)), _connector='OR'), name='staff_left_on_matches_status'), models.CheckConstraint(condition=models.Q(('left_on__isnull', True), ('joined_on__isnull', True), ('left_on__gte', models.F('joined_on')), _connector='OR'), name='staff_leaves_after_joining')],
            },
        ),
    ]
