# Generated by Django 6.1.1 on 2026-09-30 14:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_program_attendance_mode'),
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Inclusive.')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'hr_fiscal_year',
                'ordering': ['-start_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=True, help_text='Unpaid leave is deducted by payroll.')),
                ('annual_quota', models.DecimalField(blank=True, decimal_places=1, help_text='Days a fiscal year. Empty: unlimited.', max_digits=5, null=True)),
                ('carry_forward_max', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Unused days that move to next year, at most.', max_digits=5)),
                ('prorate_for_joiners', models.BooleanField(default=True, help_text='Someone joining mid-year gets a share of the quota.')),
                ('allow_half_day', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], help_text='Only staff of this gender (maternity, paternity). Empty: everyone.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'hr_leave_type',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='Inclusive.')),
                ('half_day', models.BooleanField(default=False)),
                ('days', models.DecimalField(decimal_places=1, help_text="Working days taken: weekends and holidays don't count.", max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='hr.fiscalyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr.leavetype')),
            ],
            options={
                'db_table': 'hr_leave_request',
                'ordering': ['-start_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitled', models.DecimalField(blank=True, decimal_places=1, help_text='Empty: the type has no quota.', max_digits=6, null=True)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('adjustment', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Added or removed by hand (with a reason, in the audit log).', max_digits=6)),
                ('used', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_balances', to='hr.fiscalyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='hr.leavetype')),
            ],
            options={
                'db_table': 'hr_leave_balance',
                'ordering': ['staff_id', 'leave_type__name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'hr_position',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('permanent', 'Permanent'), ('probation', 'Probation'), ('temporary', 'Temporary'), ('contract', 'Fixed-term contract'), ('part_time', 'Part-time')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Inclusive. Empty: open-ended.', null=True)),
                ('probation_ends_on', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='Appointment letter number, etc.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('ended_reason', models.CharField(blank=True, max_length=255)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='hr.position')),
            ],
            options={
                'db_table': 'hr_contract',
                'ordering': ['staff_id', '-start_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('citizenship', 'Citizenship'), ('pan', 'PAN card'), ('passport', 'Passport'), ('appointment_letter', 'Appointment letter'), ('certificate', 'Academic certificate'), ('license', 'License (teaching, driving …)'), ('cv', 'CV'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('issued_by', models.CharField(blank=True, max_length=150)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, help_text='Until file storage exists: where the scan is kept.')),
                ('notes', models.TextField(blank=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
            ],
            options={
                'db_table': 'hr_staff_document',
                'ordering': ['staff_id', 'kind', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('tax_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married / couple')], default='single', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('bank_branch', models.CharField(blank=True, max_length=150)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('ssf_number', models.CharField(blank=True, help_text='Social Security Fund', max_length=50)),
                ('pf_number', models.CharField(blank=True, help_text='Provident Fund', max_length=50)),
                ('cit_number', models.CharField(blank=True, help_text='Citizen Investment Trust', max_length=50)),
                ('citizenship_number', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='staff.staffmember')),
            ],
            options={
                'db_table': 'hr_employee_profile',
                'ordering': ['staff__first_name', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('staff',), name='uniq_hr_profile_per_staff')],
            },
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'name'), name='uniq_hr_fiscal_year_name'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='hr_fiscal_year_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_hr_leave_type_code'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.CheckConstraint(condition=models.Q(('annual_quota__isnull', True), ('annual_quota__gte', 0), _connector='OR'), name='hr_leave_quota_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.CheckConstraint(condition=models.Q(('carry_forward_max__gte', 0)), name='hr_leave_carry_not_negative'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['organization', 'status'], name='hr_leave_re_organiz_a24f70_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['staff', 'start_date'], name='hr_leave_re_staff_i_f36e7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='hr_leave_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('half_day', False), ('end_date', models.F('start_date')), _connector='OR'), name='hr_leave_half_day_is_one_day'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('days__gt', 0)), name='hr_leave_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('staff', 'leave_type', 'fiscal_year'), name='uniq_hr_leave_balance'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.CheckConstraint(condition=models.Q(('used__gte', 0)), name='hr_leave_used_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_hr_position_code'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization', 'start_date'], name='hr_contract_organiz_94e41f_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='hr_contract_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='staffdocument',
            index=models.Index(fields=['organization', 'expires_on'], name='hr_staff_do_organiz_0afaae_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffdocument',
            constraint=models.CheckConstraint(condition=models.Q(('expires_on__isnull', True), ('issued_on__isnull', True), ('expires_on__gte', models.F('issued_on')), _connector='OR'), name='hr_document_dates_ordered'),
        ),
    ]
