# Generated by Django 6.1.1 on 2026-10-02 13:41

import core.files.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_one_main_campus_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(max_length=200, storage=core.files.models.private_storage, upload_to=core.files.models._path)),
                ('name', models.CharField(help_text='The name it was uploaded with, cleaned.', max_length=150)),
                ('content_type', models.CharField(help_text="From the file's own bytes, not the client.", max_length=100)),
                ('extension', models.CharField(max_length=10)),
                ('size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('purpose', models.CharField(help_text='What it was uploaded for, e.g. resume.', max_length=30)),
                ('owner_type', models.CharField(blank=True, help_text='What it is attached to, once it is.', max_length=50)),
                ('owner_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Empty for a public form (no account).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files_stored_file',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='files_store_owner_t_c0b879_idx')],
            },
        ),
    ]
