# Generated by Django 6.1.1 on 2026-09-27 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_one_main_campus_per_organization'),
        ('staff', '0001_initial'),
        ('students', '0002_enrollment_section_alter_enrollment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('achievement', 'Achievement'), ('badge', 'Badge'), ('title', 'Title')], default='badge', max_length=12)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='A short name for the client to pick an icon by.', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'events_award',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Being set up'), ('published', 'Published'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10)),
                ('registration_mode', models.CharField(choices=[('none', 'No sign-up'), ('open', 'Open: confirmed straight away'), ('approval', 'Needs approval')], default='open', max_length=10)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizations.campus')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('organized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='staff.staffmember')),
            ],
            options={
                'db_table': 'events_event',
                'ordering': ['-start_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='events.event')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'event attendance',
                'db_table': 'events_attendance',
                'ordering': ['event_id', 'student_id'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'event categories',
                'db_table': 'events_category',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventcategory'),
        ),
        migrations.CreateModel(
            name='AwardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('threshold_kind', models.CharField(choices=[('points_total', 'Total points'), ('events_attended', 'Events attended'), ('events_won', 'Events won')], max_length=16)),
                ('threshold_value', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='events.award')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.eventcategory')),
            ],
            options={
                'db_table': 'events_award_rule',
                'ordering': ['award_id', 'threshold_value'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('winner', 'Winner'), ('runner_up', 'Runner-up'), ('organizer', 'Organizer'), ('volunteer', 'Volunteer')], default='participant', max_length=12)),
                ('position', models.PositiveSmallIntegerField(blank=True, help_text='1st, 2nd, 3rd, ... if placed.', null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participation', to='students.student')),
            ],
            options={
                'db_table': 'events_participation',
                'ordering': ['event_id', 'role', 'position'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=10)),
                ('note', models.CharField(blank=True, help_text="From the student, e.g. why they're applying.", max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=255)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='students.student')),
            ],
            options={
                'db_table': 'events_registration',
                'ordering': ['event_id', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('attendance', 'Attending an event'), ('participation', 'A participation role'), ('manual', 'Given by hand')], default='attendance', max_length=14)),
                ('role', models.CharField(blank=True, choices=[('participant', 'Participant'), ('winner', 'Winner'), ('runner_up', 'Runner-up'), ('organizer', 'Organizer'), ('volunteer', 'Volunteer')], max_length=12, null=True)),
                ('points', models.IntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.eventcategory')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'db_table': 'events_point_rule',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_entries', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_entries', to='students.student')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='events.pointrule')),
            ],
            options={
                'db_table': 'events_point_entry',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StudentAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_at', models.DateTimeField()),
                ('ended_on', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holders', to='events.award')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('rule', models.ForeignKey(blank=True, help_text='Empty: granted by hand.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='events.awardrule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='students.student')),
            ],
            options={
                'db_table': 'events_student_award',
                'ordering': ['-awarded_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='students.student')),
            ],
            options={
                'db_table': 'events_student_points',
                'ordering': ['-total'],
            },
        ),
        migrations.AddConstraint(
            model_name='award',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_award_code'),
        ),
        migrations.AddConstraint(
            model_name='eventattendance',
            constraint=models.UniqueConstraint(fields=('event', 'student'), name='uniq_event_attendance'),
        ),
        migrations.AddConstraint(
            model_name='eventcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'code'), name='uniq_event_category_code'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'campus', 'start_at'], name='events_even_organiz_639b2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gte', models.F('start_at'))), name='event_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='awardrule',
            constraint=models.CheckConstraint(condition=models.Q(('threshold_value__gt', 0)), name='award_rule_threshold_positive'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(fields=('event', 'student', 'role'), name='uniq_event_participation'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'withdrawn'), _negated=True), fields=('event', 'student'), name='uniq_live_event_registration'),
        ),
        migrations.AddConstraint(
            model_name='pointrule',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', 0)), name='point_rule_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='pointrule',
            constraint=models.CheckConstraint(condition=models.Q(('source', 'participation'), ('role__isnull', True), _connector='OR'), name='point_rule_role_needs_participation'),
        ),
        migrations.AddConstraint(
            model_name='pointentry',
            constraint=models.CheckConstraint(condition=models.Q(('points', 0), _negated=True), name='point_entry_not_zero'),
        ),
        migrations.AddConstraint(
            model_name='studentaward',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_on__isnull', True)), fields=('student', 'award'), name='uniq_open_student_award'),
        ),
    ]
